version: '3'

services:

  server:
    image: grpc-greeter:${TAG:-latest}
    build:
      dockerfile: GrpcGreeter/Dockerfile
      context: .
    expose:
      - '80'
    ports:
      - '5002:80'
    environment:
      - ASPNETCORE_URLS=http://+:80

  worker:
    image: grpc-greeter-worker:${TAG:-latest}
    build:
      dockerfile: GrpcGreeterWorker/Dockerfile
      context: .
    depends_on:
      - server
    environment:
      - GREETER_SERVICE_HOST=http://server:80